### ISSUE TITLE
Training code and details

### ISSUE THREAD

**Issue by ariel415el** [LabForComputationalVision/memorization_generalization_in_diffusion_models#2]
Hello and thank you for this great work.

How did you train the denoisers? can you share the training code for the denoisers?
Also how much time/compute did it take to train on the 10^5 80x80 celebA images

**Comment by Zahra-Kadkhodaie** [comment]
Hello! Thanks for your interest in our work. We will share the train code tomorrow. Training was done on 4 a100 GPUs in parallel. Each epoch took around 1 min. So for 1000 epochs it takes ~16 hours.
